export const actionType = {
    LAY_DANH_MUC_KHOA_HOC: 'LAY_DANH_MUC_KHOA_HOC',
    LAY_DANH_SACH_KHOA_HOC: 'LAY_DANH_SACH_KHOA_HOC',
    XOA_KHOA_HOC: 'XOA_KHOA_HOC',
    TIM_KIEM_KHOA_HOC: 'TIM_KIEM_KHOA_HOC',
    LAY_CHI_TIET_KHOA_HOC: 'LAY_CHI_TIET_KHOA_HOC',
    LAY_DANH_SACH_KHOA_HOC_THEO_MA_DANH_MUC:'LAY_DANH_SACH_KHOA_HOC_THEO_MA_DANH_MUC',
    CHON_KHOA_HOC: 'CHON_KHOA_HOC',
    SET_LOADING:'SET_LOADING',
    DANG_KY_KHOA_HOC:'DANG_KY_KHOA_HOC',
}