export const actionType = {
  DANG_NHAP: "DANG_NHAP",
  DANG_KY: "DANG_KY",
  DANG_XUAT: "DANG_XUAT",
  LAY_DANH_SACH_NGUOI_DUNG: "LAY_DANH_SACH_NGUOI_DUNG",
  TIM_KIEM_NGUOI_DUNG: "TIM_KIEM_NGUOI_DUNG",
  LAY_DANH_SACH_KHOA_HOC_DA_GHI_DANH: "LAY_DANH_SACH_KHOA_HOC_DA_GHI_DANH",
  LAY_DANH_SACH_KHOA_HOC_CHO_XET_DUYET: "LAY_DANH_SACH_KHOA_HOC_CHO_XET_DUYET",
  DA_DANG_NHAP: "DA_DANG_NHAP",
  LAY_THONG_TIN_NGUOI_DUNG: "LAY_THONG_TIN_NGUOI_DUNG",
  THEM_NGUOI_DUNG: "THEM_NGUOI_DUNG",
  SUA_THONG_TIN_NGUOI_DUNG: "SUA_THONG_TIN_NGUOI_DUNG",
  XOA_NGUOI_DUNG: "XOA_NGUOI_DUNG",
  XAC_THUC_GHI_DANH: "XAC_THUC_GHI_DANH",
  HUY_GHI_DANH: "HUY_GHI_DANH",
  LAY_DANH_SACH_LOAI_NGUOI_DUNG: "LAY_DANH_SACH_LOAI_NGUOI_DUNG"
};
